# This is a basic workflow to help you get started with Actions

name: Greet New Members

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  welcome:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Comment to post on an individual's first issue
          issue-message: ã‚ˆã†ã“ãã†Findadocï¼ğŸ˜Š
          # Comment to post on an individual's first pull request
          pr-message: ã‚ˆã†ã“ãã†ã¸Findadocï¼ğŸ˜Š
